version: '2'
services:
  fintechproject1-app:
    image: fintechproject1
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://fintechproject1-mysql:3306/fintechproject1?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://fintechproject1-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://fintechproject1-elasticsearch:9200
    ports:
      - 8080:8080
  fintechproject1-mysql:
    extends:
      file: mysql.yml
      service: fintechproject1-mysql
  fintechproject1-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: fintechproject1-elasticsearch
